#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/Users/kristofferaas/.cursor/worktrees/deep-stortinget/1761328465043-8c1e77/node_modules/.pnpm/esbuild@0.25.4/node_modules/esbuild/bin/node_modules:/Users/kristofferaas/.cursor/worktrees/deep-stortinget/1761328465043-8c1e77/node_modules/.pnpm/esbuild@0.25.4/node_modules/esbuild/node_modules:/Users/kristofferaas/.cursor/worktrees/deep-stortinget/1761328465043-8c1e77/node_modules/.pnpm/esbuild@0.25.4/node_modules:/Users/kristofferaas/.cursor/worktrees/deep-stortinget/1761328465043-8c1e77/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="/Users/kristofferaas/.cursor/worktrees/deep-stortinget/1761328465043-8c1e77/node_modules/.pnpm/esbuild@0.25.4/node_modules/esbuild/bin/node_modules:/Users/kristofferaas/.cursor/worktrees/deep-stortinget/1761328465043-8c1e77/node_modules/.pnpm/esbuild@0.25.4/node_modules/esbuild/node_modules:/Users/kristofferaas/.cursor/worktrees/deep-stortinget/1761328465043-8c1e77/node_modules/.pnpm/esbuild@0.25.4/node_modules:/Users/kristofferaas/.cursor/worktrees/deep-stortinget/1761328465043-8c1e77/node_modules/.pnpm/node_modules:$NODE_PATH"
fi
if [ -x "$basedir/node" ]; then
  exec "$basedir/node"  "$basedir/../../bin/esbuild" "$@"
else
  exec node  "$basedir/../../bin/esbuild" "$@"
fi
